### ISSUE TITLE
Membership Onboarding

### ISSUE THREAD

**Issue by burrrata** [pythonpete32/aragoncoop_governance#5]
I like Proposal 1
- Contributor signals intent to become a member
- Contributor enters a probationary period
- Contributor makes an application to for membership
- After earning x MRT members collectively make a desisition to mint (or not) a new MBR token for the contributor

Currently we have no way to distribute MRT, so let's skip that part for now. Otherwise I think it looks good. 

<br>

In addition, we would do well to create criteria against which to evaluate new members. 
- why do they want to join
- how do they plan on contributing to the mission/objectives of the group
- what have they done so far to demonstrate the above intent?

**Comment by burrrata** [comment]
Once we have the onboarding protocol finalized, it would make sense that all current members would need to approve the current bylaws and membership agreements and then be included in the organization
- this will involve the onboarding flow of signalling why they want to join, how they want to contribute, and what they have done so far to contribute

Since there are some members who actively want to leave, and some who are literally just checked out and not participating, we need to define a protocol around this. I think that looks like:
- First, members who want to leave can do so and skip the onboarding protocol. Their tokens will be burned immediately. 
- Then, members who want to stay need to take actions to stay. This involves reading and signing the membership agreement and going through the onboarding flow. This will all happen at once, so every member can vote in every other member. Members who receive enough votes (say > 66%) will maintain membership and those who do not will be removed.

This way everyone can move forward together with a group that has all agreed to the same membership guidelines, all wants to work together, and is all on the same page.

**Comment by burrrata** [comment]
### Open Question

Is the round robin style voting described here viable, or once a member leaves will their tokens be removed and thus their votes nullified? 
- actually, if someone does not make it through the process then it shows that their votes were not valued anyways, whereas members who do make it through (assuming this is almost everyone) will have votes that remain valid, and thus it's a non issue

**Comment by burrrata** [comment]
In the future we could have a "probationary period" for the onboarding process, but atm I think it makes sense to keep it simple.

**Comment by pythonpete32** [comment]
I was thinking the same

**Comment by burrrata** [comment]
Closing this because we got the draft dialed in. Please open it back up if you have further thoughts/questions though :)
