### ISSUE TITLE
Membership Offboarding

### ISSUE THREAD

**Issue by burrrata** [pythonpete32/aragoncoop_governance#7]
First! 
- we need @lkngtn to initialize the token burning feature in the DAO so that membership can be revoked

Then, we need to create:
- a protocol for members to voluntarily revoke their own membership
- a protocol for current members to forcibly remove a member

**Comment by burrrata** [comment]
Asked about the technical specifics of the DAO just now. Waiting for a response.

**Comment by burrrata** [comment]
Closing because the draft is ready and the protocol defined therein is clearly within the capabilities of Aragon DAOs. Please open this back up though if you have further questions/comments/concerns :)

**Comment by julianbrooks** [comment]
As this has never been defined, may I ask: What is the process for burning MBR tokens, can we do this now?
